; Lucas de Souza Moraes - 538464
; Luana Duarte Santana Farias - 576485
	LIST   P=PIC16F628A
#INCLUDE <P16F628A.INC> 		;P16F628A
	__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _BODEN_OFF & _LVP_OFF & _CP_OFF & _MCLRE_OFF & _DATA_CP_OFF
	;ou __CONFIG H'3F10'
  #DEFINE BANK0 BCF STATUS,RP0  					 ;SET BANK 0
  #DEFINE BANK1 BSF STATUS,RP0  					 ;SET BANK 1
  #DEFINE BUTTON PORTA,D'2'                   ;0 H 1 L
	CBLOCK	0x20		;ENDERECO INICIAL DA MEMORIA
  D1              ;DELAY1
  D2              ;DELAY2
  D3              ;DELAY3
  AUX             ;AUXILIAR
	ENDC						;FIM DO BLOCO DE MEMORIA
	ORG	0x00				;ENDERECO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
;*******************************************************************
INICIO
	    CLRF	PORTA				 ;LIMPA A PORTA
	    CLRF	PORTB				 ;LIMPA A PORTB
		CLRF TRISA
		CLRF TRISB
	    BANK1
		MOVLW	B'00000100'
		MOVWF TRISA				 ;DEFINE RA2 ENTRADA DE PORTA E O RESTO SAIDAS
		MOVLW	B'00000000'
	    MOVWF TRISB				 ;DEFINE SAIDAS DE PORTB
		MOVLW	B'00000000'
		MOVWF INTCON 			 ;DESLIGAR INTERRUPCOES
	    BANK0
		MOVLW 	B'00000111'
		MOVWF CMCON				 ;COMPARADOR ANALOGICO
;*******************************************************************
LOOP
		CALL TESTE
		GOTO LOOP
CICLO1
		MOVLW	B'00000000'		;S1 VERDE,S2 VERMELHO
		MOVWF	PORTB
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
		GOTO LOOP
;*******************************************************************
; DELAY: REALIZA DELAY DE ACORDO COM CYCLES (RECALCULAR)
; ACRECENTANDO VALORES A REGISTRADOR
; E DIMUINDO ELES ATE 0
; NOTE: MOVLW+1CYCLE
;				MOVWF+1CYCLE
;				DECFSZ+2CYCLE (AO PULAR, SEMPRE 1 CYCLE)
;				BDSFC +2 CYCLES
;SE PUDER USAR QUEBRA DE CICLOS ( D1,D2,D3 VALEM OS VALORES EM HEXA)
;QUEBRAS DE $+2 CICLOS ENTRE OS GOTO
;*******************************************************************
DELAY
            MOVLW	D'6' ;0x07
  	        MOVWF	D1
			MOVLW   D'19' ;0x2F
  	        MOVWF	D2
  	        MOVLW	D'169' ;0x03
  	        MOVWF	D3
DELAY_0
			DECFSZ	D3, F
          	GOTO	DELAY_0
          	DECFSZ	D2, F
          	GOTO	DELAY_0
          	DECFSZ	D1, F
          	GOTO    DELAY_0
         	NOP
		;	NOP
  	        RETURN
TESTE
		   ;MOVLW	0x07
		   ;MOVWF	AUX
FOR1
	MOVLW	B'11111111'		;S1 VERDE,S2 VERMELHO
	MOVWF	PORTB
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
	BTFSS BUTTON
	;GOTO	BOTAO_LIB	;N�O, ENT�O TRATA BOT�O LIBERADO
	;GOTO	BOTAO_PRES	;SIM, ENT�O TRATA BOT�O PRESSIONADO
	CALL CICLO1
	DECFSZ AUX,F
	;GOTO FOR1
	RETURN


BOTAO_LIB

	MOVLW	B'00000000'		;APAGA O LED
	MOVWF	PORTB
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY

	GOTO 	LOOP		;RETORNA AO LOOP PRINCIPAL

BOTAO_PRES
	MOVLW	B'01010101'		;APAGA O LED
    MOVWF	PORTB
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
CALL DELAY
	GOTO 	LOOP
	END
