; Lucas de Souza Moraes - 538464
; Luana Duarte Santana Farias - 576485
LIST   P=PIC16F628A
#INCLUDE <P16F628A.INC> 		;P16F628A
	__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _BODEN_OFF & _LVP_OFF & _CP_OFF & _MCLRE_OFF & _DATA_CP_OFF
	;ou __CONFIG H'3F10'
  #DEFINE BANK0 BCF STATUS,RP0  					 ;SET BANK 0
  #DEFINE BANK1 BSF STATUS,RP0  					 ;SET BANK 1
  #DEFINE BUTTON PORTA,D'2'                ;0 H 1 L
	CBLOCK	0x20		;ENDERECO INICIAL DA MEMORIA
  D1              ;DELAY1
  D2              ;DELAY2
  D3              ;DELAY3
  AUX             ;AUXILIAR
	ENDC						;FIM DO BLOCO DE MEMORIA
	ORG	0x00				    ;ENDERECO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
;*******************************************************************
INICIO:
	    CLRF	PORTA				 ;LIMPA A PORTA
	    CLRF	PORTB				 ;LIMPA A PORTB
		CLRF  TRISA
		CLRF  TRISB
	    BANK1
			MOVLW	B'00000100'
			MOVWF TRISA				 ;DEFINE RA2 ENTRADA DE PORTA E O RESTO SAIDAS
			MOVLW	B'00000000'
	        MOVWF TRISB				 ;DEFINE SAIDAS DE PORTB
			MOVLW B'00000000'
			MOVWF INTCON       ;DESLIGAR INTERRUPCOES
	    BANK0
			MOVLW B'00000111'
			MOVWF CMCON        ;COMPARADOR ANALOGICO
;*******************************************************************
LOOP
MOVLW	D'7'
MOVWF	AUX
FOR1
		 MOVLW	B'00001100'		;S1 VERDE,S2 VERMELHO
         MOVWF	PORTB
         CALL DELAY
		 BTFSS BUTTON
		 CALL CICLO_1
         DECFSZ AUX,F
         GOTO FOR1
MOVLW	D'3'
MOVWF	AUX
FOR2
		 MOVLW	B'00001010'		;S1 AMARELO,S2 VERMELHO
         MOVWF	PORTB
         CALL DELAY
		 BTFSS BUTTON
		 CALL CICLO_2
         DECFSZ AUX,F
         GOTO FOR2
MOVLW	D'2'
MOVWF	AUX
FOR3
		 MOVLW	B'00100001'		;S1 VERMELHO,S2 VERDE
         MOVWF	PORTB
         CALL DELAY
		 BTFSS BUTTON
		 CALL CICLO_3
         DECFSZ AUX,F
         GOTO FOR3
MOVLW	D'2'
MOVWF	AUX
FOR4
		 MOVLW	B'00010001'		;S1 VERMELHO, S2 AMARELO
         MOVWF	PORTB
         CALL DELAY
		 BTFSS BUTTON
		 CALL CICLO_3
         DECFSZ AUX,F
         GOTO FOR4
GOTO LOOP
;*******************************************************************
;SUBROTINAS
;*******************************************************************
CICLO_1
 	MOVLW	D'3'
    MOVWF	AUX
FORC1_2
		  MOVLW	B'00001010'		;S1 AMARELO,S2 VERMELHO
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC1_2
  MOVLW	D'3'
  MOVWF	AUX
FORC1_3
		  MOVLW	B'00100001'		;S1 VERMELHO,S2 VERDE
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC1_3
  CALL DELAY
  MOVLW	D'3'
  MOVWF	AUX
FORC1_4
	 	  MOVLW	B'00010001'		;S1 VERMELHO, S2 AMARELO
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC1_4
  MOVLW	D'4'
  MOVWF	AUX
FORC1_1
	 	  MOVLW	B'00001100'		;S1 VERDE,S2 VERMELHO
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC1_1
  GOTO LOOP
CICLO_2
  MOVLW	D'3'
  MOVWF	AUX
FORC2_3
	 	  MOVLW	B'00100001'		;S1 VERMELHO,S2 VERDE
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC2_3
  MOVLW	D'3'
  MOVWF	AUX
  NOP
FORC2_4
		  MOVLW	B'00010001'		;S1 VERMELHO, S2 AMARELO
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC2_4
  MOVLW	D'4'
  MOVWF	AUX
FORC2_1
		  MOVLW	B'00001100'		;S1 VERDE,S2 VERMELHO
  		  MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC2_1
	GOTO LOOP
CICLO_3
  MOVLW	D'3'
  MOVWF	AUX
FORC3_3
          MOVLW	B'00100001'		;S1 VERMELHO,S2 VERDE
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC3_3
          CALL DELAY
  MOVLW	D'3'
  MOVWF	AUX
FORC3_4
		  MOVLW	B'00010001'		;S1 VERMELHO, S2 AMARELO
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC3_4
  MOVLW	D'4'
  MOVWF	AUX
FORC3_1
		  MOVLW	B'00001100'		;S1 VERDE,S2 VERMELHO
          MOVWF	PORTB
          CALL DELAY
          DECFSZ AUX,F
          GOTO FORC3_1
  GOTO LOOP
;*******************************************************************
; DELAY: REALIZA DELAY DE ACORDO COM CYCLES (RECALCULAR)
; ACRECENTANDO VALORES A REGISTRADOR
; E DIMUINDO ELES ATE 0
; NOTE: MOVLW+1CYCLE
;				MOVWF+1CYCLE
;				DECFSZ+2CYCLE (AO PULAR, SEMPRE 1 CYCLE)
;				BDSFC +2 CYCLES
;SE PUDER USAR QUEBRA DE CICLOS ( D1,D2,D3 VALEM OS VALORES EM HEXA)
;QUEBRAS DE $+2 CICLOS ENTRE OS GOTO
;*******************************************************************
DELAY
      MOVLW	D'6'   ;0x07
  	  MOVWF	D1
	  MOVLW D'19'  ;0x2F
  	  MOVWF	D2
  	  MOVLW	D'169' ;0x03
  	  MOVWF	D3
DELAY_0
	  DECFSZ	D3, F
      GOTO	DELAY_0
      DECFSZ	D2, F
      GOTO	DELAY_0
      DECFSZ	D1, F
      GOTO    DELAY_0
      NOP
	  ;NOP
  	  RETURN
END
